################################################################################
# Node-RED Stack or Compose 
################################################################################
# docker stack deploy node-red --compose-file docker-compose-node-red.yml
# docker-compose -f docker-compose-node-red.yml -p myNoderedProject up
################################################################################
version: "3.7"

services:
  node-red:
    build: .
    container_name: node-red
    image: local-nodered-custom
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "1880:1880"
      - "4545:4545"
      # Forward ports 5000 to 5010 for multiple instances
      - "5000:5000"
      - "5001:5001"
      - "5002:5002"
      - "5003:5003"
      - "5004:5004"
      - "5005:5005"
      - "5006:5006"
      - "5007:5007"
      - "5008:5008"
      - "5009:5009"
      - "5010:5010"
    networks:
      - node-red-net
    volumes:
      - node-red-data:/data
    # Install node-red-contrib-open-protocol
    command: sh -c "cd /data && npm install node-red-contrib-open-protocol && npm start"

volumes:
  node-red-data:

networks:
  node-red-net:
